version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: src/WatchStore.API/Dockerfile
      args:
        - BUILD_CONFIGURATION=Release
      cache_from:
        - watchstore-api:latest
    container_name: watchstore-api
    image: watchstore-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=WatchStoreDb;Username=postgres;Password=postgres
    ports:
      - "5000:80"
    depends_on:
      - postgres
    cpu_count: 4
    mem_limit: 512m

  postgres:
    image: postgres:15-alpine
    container_name: watchstore-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=WatchStoreDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=200'
    cpu_count: 2
    mem_limit: 256m

volumes:
  postgres_data:
    driver: local
